namespace MarketLens.Core.Domain;

public sealed record TickerMetadataEntry(
    string Ticker,
    string CompanyName,
    string Cik,
    string? IrFeedUrl,
    IReadOnlyList<string> Aliases);

public static class TickerMetadata
{
    public static readonly IReadOnlyList<TickerMetadataEntry> Known = new List<TickerMetadataEntry>
    {
        new("A",     "Agilent Technologies",               "0001090872", null, ["A", "Agilent Technologies"]),
        new("AAPL",  "Apple Inc.",                         "0000320193", "https://www.apple.com/newsroom/rss-feed.rss", ["AAPL", "Apple"]),
        new("ABBV",  "AbbVie",                             "0001551152", null, ["ABBV", "AbbVie"]),
        new("ABG",   "Asbury Automotive Group Inc.",       "0001144980", null, ["ABG", "Asbury Automotive", "Asbury"]),
        new("ABNB",  "Airbnb",                             "0001559720", null, ["ABNB", "Airbnb"]),
        new("ABT",   "Abbott Laboratories",                "0000001800", null, ["ABT", "Abbott Laboratories"]),
        new("ACGL",  "Arch Capital Group",                 "0000947484", null, ["ACGL", "Arch Capital Group"]),
        new("ACN",   "Accenture",                          "0001467373", null, ["ACN", "Accenture"]),
        new("ADBE",  "Adobe Inc.",                         "0000796343", null, ["ADBE", "Adobe Inc."]),
        new("ADI",   "Analog Devices",                     "0000006281", null, ["ADI", "Analog Devices"]),
        new("ADM",   "Archer Daniels Midland",             "0000007084", null, ["ADM", "Archer Daniels Midland"]),
        new("ADP",   "Automatic Data Processing",          "0000008670", null, ["ADP", "Automatic Data Processing"]),
        new("ADSK",  "Autodesk",                           "0000769397", null, ["ADSK", "Autodesk"]),
        new("AEE",   "Ameren",                             "0001002910", null, ["AEE", "Ameren"]),
        new("AEM",   "Agnico Eagle Mines Limited",         "0000002809", null, ["AEM", "Agnico Eagle", "Agnico"]),
        new("AEP",   "American Electric Power",            "0000004904", null, ["AEP", "American Electric Power"]),
        new("AES",   "AES Corporation",                    "0000874761", null, ["AES", "AES Corporation"]),
        new("AFL",   "Aflac",                              "0000004977", null, ["AFL", "Aflac"]),
        new("AIG",   "American International Group",       "0000005272", null, ["AIG", "American International Group"]),
        new("AIZ",   "Assurant",                           "0001267238", null, ["AIZ", "Assurant"]),
        new("AJG",   "Arthur J. Gallagher & Co.",          "0000354190", null, ["AJG", "Arthur J. Gallagher & Co."]),
        new("AKAM",  "Akamai Technologies",                "0001086222", null, ["AKAM", "Akamai Technologies"]),
        new("ALB",   "Albemarle Corporation",              "0000915913", null, ["ALB", "Albemarle Corporation"]),
        new("ALGN",  "Align Technology",                   "0001097149", null, ["ALGN", "Align Technology"]),
        new("ALL",   "Allstate",                           "0000899051", null, ["ALL", "Allstate"]),
        new("ALLE",  "Allegion",                           "0001579241", null, ["ALLE", "Allegion"]),
        new("AMAT",  "Applied Materials Inc.",             "0000006951", null, ["AMAT", "Applied Materials"]),
        new("AMCR",  "Amcor",                              "0001748790", null, ["AMCR", "Amcor"]),
        new("AMD",   "Advanced Micro Devices Inc.",        "0000002488", "https://ir.amd.com/rss", ["AMD", "Advanced Micro Devices"]),
        new("AME",   "Ametek",                             "0001037868", null, ["AME", "Ametek"]),
        new("AMGN",  "Amgen",                              "0000318154", null, ["AMGN", "Amgen"]),
        new("AMP",   "Ameriprise Financial",               "0000820027", null, ["AMP", "Ameriprise Financial"]),
        new("AMT",   "American Tower",                     "0001053507", null, ["AMT", "American Tower"]),
        new("AMZN",  "Amazon.com Inc.",                    "0001018724", "https://press.aboutamazon.com/rss/news-releases.xml", ["AMZN", "Amazon", "Amazon.com"]),
        new("AN",    "AutoNation Inc.",                    "0000350698", null, ["AN", "AutoNation"]),
        new("ANET",  "Arista Networks Inc.",               "0001596532", null, ["ANET", "Arista Networks", "Arista"]),
        new("AON",   "Aon plc",                            "0000315293", null, ["AON", "Aon plc"]),
        new("AOS",   "A. O. Smith",                        "0000091142", null, ["AOS", "A. O. Smith"]),
        new("APA",   "APA Corporation",                    "0001841666", null, ["APA", "APA Corporation"]),
        new("APD",   "Air Products",                       "0000002969", null, ["APD", "Air Products"]),
        new("APH",   "Amphenol",                           "0000820313", null, ["APH", "Amphenol"]),
        new("APO",   "Apollo Global Management",           "0001858681", null, ["APO", "Apollo Global Management"]),
        new("APP",   "AppLovin",                           "0001751008", null, ["APP", "AppLovin"]),
        new("APTV",  "Aptiv",                              "0001521332", null, ["APTV", "Aptiv"]),
        new("ARE",   "Alexandria Real Estate Equities",    "0001035443", null, ["ARE", "Alexandria Real Estate Equities"]),
        new("ARES",  "Ares Management",                    "0001176948", null, ["ARES", "Ares Management"]),
        new("ARM",   "Arm Holdings plc",                   "0001973239", null, ["ARM", "Arm Holdings", "Arm"]),
        new("ASML",  "ASML Holding NV",                    "0000937966", null, ["ASML", "ASML Holding"]),
        new("ATO",   "Atmos Energy",                       "0000731802", null, ["ATO", "Atmos Energy"]),
        new("AVB",   "AvalonBay Communities",              "0000915912", null, ["AVB", "AvalonBay Communities"]),
        new("AVGO",  "Broadcom Inc.",                      "0001730168", "https://investors.broadcom.com/rss/news-releases.xml", ["AVGO", "Broadcom"]),
        new("AVY",   "Avery Dennison",                     "0000008818", null, ["AVY", "Avery Dennison"]),
        new("AWK",   "American Water Works",               "0001410636", null, ["AWK", "American Water Works"]),
        new("AXON",  "Axon Enterprise",                    "0001069183", null, ["AXON", "Axon Enterprise"]),
        new("AXP",   "American Express",                   "0000004962", null, ["AXP", "American Express"]),
        new("AZO",   "AutoZone",                           "0000866787", null, ["AZO", "AutoZone"]),
        new("BA",    "Boeing",                             "0000012927", null, ["BA", "Boeing"]),
        new("BAC",   "Bank of America",                    "0000070858", null, ["BAC", "Bank of America"]),
        new("BALL",  "Ball Corporation",                   "0000009389", null, ["BALL", "Ball Corporation"]),
        new("BAX",   "Baxter International",               "0000010456", null, ["BAX", "Baxter International"]),
        new("BBY",   "Best Buy",                           "0000764478", null, ["BBY", "Best Buy"]),
        new("BDX",   "Becton Dickinson",                   "0000010795", null, ["BDX", "Becton Dickinson"]),
        new("BEN",   "Franklin Resources",                 "0000038777", null, ["BEN", "Franklin Resources"]),
        new("BF.B",  "Brown–Forman",                       "0000014693", null, ["BF.B", "Brown–Forman"]),
        new("BG",    "Bunge Global",                       "0001996862", null, ["BG", "Bunge Global"]),
        new("BHP",   "BHP Group Limited",                  "0000811809", null, ["BHP", "BHP Group", "BHP Billiton"]),
        new("BIIB",  "Biogen",                             "0000875045", null, ["BIIB", "Biogen"]),
        new("BK",    "BNY Mellon",                         "0001390777", null, ["BK", "BNY Mellon"]),
        new("BKNG",  "Booking Holdings",                   "0001075531", null, ["BKNG", "Booking Holdings"]),
        new("BKR",   "Baker Hughes Co.",                   "0001701605", null, ["BKR", "Baker Hughes"]),
        new("BLDR",  "Builders FirstSource",               "0001316835", null, ["BLDR", "Builders FirstSource"]),
        new("BLK",   "BlackRock",                          "0002012383", null, ["BLK", "BlackRock"]),
        new("BMY",   "Bristol Myers Squibb",               "0000014272", null, ["BMY", "Bristol Myers Squibb"]),
        new("BR",    "Broadridge Financial Solutions",     "0001383312", null, ["BR", "Broadridge Financial Solutions"]),
        new("BRK.B", "Berkshire Hathaway",                 "0001067983", null, ["BRK.B", "Berkshire Hathaway"]),
        new("BRO",   "Brown & Brown",                      "0000079282", null, ["BRO", "Brown & Brown"]),
        new("BSX",   "Boston Scientific",                  "0000885725", null, ["BSX", "Boston Scientific"]),
        new("BX",    "Blackstone Inc.",                    "0001393818", null, ["BX", "Blackstone Inc."]),
        new("BXP",   "BXP, Inc.",                          "0001037540", null, ["BXP", "BXP, Inc."]),
        new("C",     "Citigroup",                          "0000831001", null, ["C", "Citigroup"]),
        new("CAG",   "Conagra Brands",                     "0000023217", null, ["CAG", "Conagra Brands"]),
        new("CAH",   "Cardinal Health",                    "0000721371", null, ["CAH", "Cardinal Health"]),
        new("CARR",  "Carrier Global",                     "0001783180", null, ["CARR", "Carrier Global"]),
        new("CASY",  "Casey's",                            "0000726958", null, ["CASY", "Casey's"]),
        new("CAT",   "Caterpillar Inc.",                   "0000018230", null, ["CAT", "Caterpillar Inc."]),
        new("CB",    "Chubb Limited",                      "0000896159", null, ["CB", "Chubb Limited"]),
        new("CBRE",  "CBRE Group",                         "0001138118", null, ["CBRE", "CBRE Group"]),
        new("CCI",   "Crown Castle",                       "0001051470", null, ["CCI", "Crown Castle"]),
        new("CCJ",   "Cameco Corp.",                       "0001009001", null, ["CCJ", "Cameco", "Cameco Corp"]),
        new("CCL",   "Carnival",                           "0000815097", null, ["CCL", "Carnival"]),
        new("CDNS",  "Cadence Design Systems",             "0000813672", null, ["CDNS", "Cadence Design Systems"]),
        new("CDW",   "CDW Corporation",                    "0001402057", null, ["CDW", "CDW Corporation"]),
        new("CEG",   "Constellation Energy",               "0001868275", null, ["CEG", "Constellation Energy"]),
        new("CF",    "CF Industries",                      "0001324404", null, ["CF", "CF Industries"]),
        new("CFG",   "Citizens Financial Group",           "0000759944", null, ["CFG", "Citizens Financial Group"]),
        new("CHD",   "Church & Dwight",                    "0000313927", null, ["CHD", "Church & Dwight"]),
        new("CHRW",  "C.H. Robinson",                      "0001043277", null, ["CHRW", "C.H. Robinson"]),
        new("CHTR",  "Charter Communications",             "0001091667", null, ["CHTR", "Charter Communications"]),
        new("CI",    "Cigna",                              "0001739940", null, ["CI", "Cigna"]),
        new("CIEN",  "Ciena",                              "0000936395", null, ["CIEN", "Ciena"]),
        new("CINF",  "Cincinnati Financial",               "0000020286", null, ["CINF", "Cincinnati Financial"]),
        new("CL",    "Colgate-Palmolive",                  "0000021665", null, ["CL", "Colgate-Palmolive"]),
        new("CLX",   "Clorox",                             "0000021076", null, ["CLX", "Clorox"]),
        new("CMCSA", "Comcast",                            "0001166691", null, ["CMCSA", "Comcast"]),
        new("CME",   "CME Group",                          "0001156375", null, ["CME", "CME Group"]),
        new("CMG",   "Chipotle Mexican Grill",             "0001058090", null, ["CMG", "Chipotle Mexican Grill"]),
        new("CMI",   "Cummins",                            "0000026172", null, ["CMI", "Cummins"]),
        new("CMS",   "CMS Energy",                         "0000811156", null, ["CMS", "CMS Energy"]),
        new("CNC",   "Centene Corporation",                "0001071739", null, ["CNC", "Centene Corporation"]),
        new("CNP",   "CenterPoint Energy",                 "0001130310", null, ["CNP", "CenterPoint Energy"]),
        new("COF",   "Capital One",                        "0000927628", null, ["COF", "Capital One"]),
        new("COHR",  "Coherent Corp.",                     "0000820318", null, ["COHR", "Coherent Corporation", "II-VI"]),
        new("COIN",  "Coinbase",                           "0001679788", null, ["COIN", "Coinbase"]),
        new("COO",   "Cooper Companies (The)",             "0000711404", null, ["COO", "Cooper Companies"]),
        new("COP",   "ConocoPhillips",                     "0001163165", null, ["COP", "ConocoPhillips", "Conoco"]),
        new("COR",   "Cencora",                            "0001140859", null, ["COR", "Cencora"]),
        new("COPX",  "Global X Copper Miners ETF",          "", null, ["COPX"]),
        new("COST",  "Costco",                             "0000909832", null, ["COST", "Costco"]),
        new("CPAY",  "Corpay",                             "0001175454", null, ["CPAY", "Corpay"]),
        new("CPB",   "Campbell's Company (The)",           "0000016732", null, ["CPB", "Campbell's Company"]),
        new("CPRT",  "Copart",                             "0000900075", null, ["CPRT", "Copart"]),
        new("CPT",   "Camden Property Trust",              "0000906345", null, ["CPT", "Camden Property Trust"]),
        new("CRH",   "CRH plc",                            "0000849395", null, ["CRH", "CRH plc"]),
        new("CRL",   "Charles River Laboratories",         "0001100682", null, ["CRL", "Charles River Laboratories"]),
        new("CRM",   "Salesforce Inc.",                    "0001108524", null, ["CRM", "Salesforce"]),
        new("CRWD",  "CrowdStrike",                        "0001535527", null, ["CRWD", "CrowdStrike"]),
        new("CRWV",  "CoreWeave Inc.",                     "0001769628", null, ["CRWV", "CoreWeave"]),
        new("CSCO",  "Cisco",                              "0000858877", null, ["CSCO", "Cisco"]),
        new("CSGP",  "CoStar Group",                       "0001057352", null, ["CSGP", "CoStar Group"]),
        new("CSX",   "CSX Corporation",                    "0000277948", null, ["CSX", "CSX Corporation"]),
        new("CTAS",  "Cintas",                             "0000723254", null, ["CTAS", "Cintas"]),
        new("CTSH",  "Cognizant",                          "0001058290", null, ["CTSH", "Cognizant"]),
        new("CTVA",  "Corteva",                            "0001755672", null, ["CTVA", "Corteva"]),
        new("CVNA",  "Carvana Co.",                        "0001690820", null, ["CVNA", "Carvana"]),
        new("CVS",   "CVS Health",                         "0000064803", null, ["CVS", "CVS Health"]),
        new("CVX",   "Chevron Corp.",                      "0000093410", null, ["CVX", "Chevron"]),
        new("D",     "Dominion Energy",                    "0000715957", null, ["D", "Dominion Energy"]),
        new("DAL",   "Delta Air Lines",                    "0000027904", null, ["DAL", "Delta Air Lines"]),
        new("DASH",  "DoorDash",                           "0001792789", null, ["DASH", "DoorDash"]),
        new("DD",    "DuPont",                             "0001666700", null, ["DD", "DuPont"]),
        new("DDOG",  "Datadog",                            "0001561550", null, ["DDOG", "Datadog"]),
        new("DE",    "Deere & Company",                    "0000315189", null, ["DE", "Deere & Company"]),
        new("DECK",  "Deckers Brands",                     "0000910521", null, ["DECK", "Deckers Brands"]),
        new("DELL",  "Dell Technologies Inc.",             "0001571996", null, ["DELL", "Dell Technologies", "Dell Inc"]),
        new("DG",    "Dollar General",                     "0000029534", null, ["DG", "Dollar General"]),
        new("DGX",   "Quest Diagnostics",                  "0001022079", null, ["DGX", "Quest Diagnostics"]),
        new("DHI",   "D. R. Horton",                       "0000882184", null, ["DHI", "D. R. Horton"]),
        new("DHR",   "Danaher Corporation",                "0000313616", null, ["DHR", "Danaher Corporation"]),
        new("DNN",   "Denison Mines Corp.",                "0001063259", null, ["DNN", "Denison Mines", "Denison"]),
        new("DIS",   "Walt Disney Company (The)",          "0001744489", null, ["DIS", "Walt Disney Company"]),
        new("DLR",   "Digital Realty",                     "0001297996", null, ["DLR", "Digital Realty"]),
        new("DLTR",  "Dollar Tree",                        "0000935703", null, ["DLTR", "Dollar Tree"]),
        new("DOC",   "Healthpeak Properties",              "0000765880", null, ["DOC", "Healthpeak Properties"]),
        new("DOV",   "Dover Corporation",                  "0000029905", null, ["DOV", "Dover Corporation"]),
        new("DOW",   "Dow Inc.",                           "0001751788", null, ["DOW", "Dow Inc."]),
        new("DPZ",   "Domino's",                           "0001286681", null, ["DPZ", "Domino's"]),
        new("DRI",   "Darden Restaurants",                 "0000940944", null, ["DRI", "Darden Restaurants"]),
        new("DTE",   "DTE Energy",                         "0000936340", null, ["DTE", "DTE Energy"]),
        new("DUK",   "Duke Energy",                        "0001326160", null, ["DUK", "Duke Energy"]),
        new("DVA",   "DaVita",                             "0000927066", null, ["DVA", "DaVita"]),
        new("DVN",   "Devon Energy",                       "0001090012", null, ["DVN", "Devon Energy"]),
        new("DXCM",  "Dexcom",                             "0001093557", null, ["DXCM", "Dexcom"]),
        new("EA",    "Electronic Arts",                    "0000712515", null, ["EA", "Electronic Arts"]),
        new("EBAY",  "eBay Inc.",                          "0001065088", null, ["EBAY", "eBay Inc."]),
        new("ECL",   "Ecolab",                             "0000031462", null, ["ECL", "Ecolab"]),
        new("ED",    "Consolidated Edison",                "0001047862", null, ["ED", "Consolidated Edison"]),
        new("EFX",   "Equifax",                            "0000033185", null, ["EFX", "Equifax"]),
        new("EG",    "Everest Group",                      "0001095073", null, ["EG", "Everest Group"]),
        new("EIX",   "Edison International",               "0000827052", null, ["EIX", "Edison International"]),
        new("EL",    "Estée Lauder Companies (The)",       "0001001250", null, ["EL", "Estée Lauder Companies"]),
        new("ELV",   "Elevance Health",                    "0001156039", null, ["ELV", "Elevance Health"]),
        new("EME",   "Emcor",                              "0000105634", null, ["EME", "Emcor"]),
        new("EMR",   "Emerson Electric",                   "0000032604", null, ["EMR", "Emerson Electric"]),
        new("EOG",   "EOG Resources Inc.",                 "0000821189", null, ["EOG", "EOG Resources"]),
        new("EPAM",  "EPAM Systems",                       "0001352010", null, ["EPAM", "EPAM Systems"]),
        new("EQIX",  "Equinix",                            "0001101239", null, ["EQIX", "Equinix"]),
        new("ERO",   "Ero Copper Corp.",                   "0001853860", null, ["ERO", "Ero Copper"]),
        new("EQR",   "Equity Residential",                 "0000906107", null, ["EQR", "Equity Residential"]),
        new("EQT",   "EQT Corporation",                    "0000033213", null, ["EQT", "EQT Corporation"]),
        new("ERIE",  "Erie Indemnity",                     "0000922621", null, ["ERIE", "Erie Indemnity"]),
        new("ES",    "Eversource Energy",                  "0000072741", null, ["ES", "Eversource Energy"]),
        new("ESS",   "Essex Property Trust",               "0000920522", null, ["ESS", "Essex Property Trust"]),
        new("ETN",   "Eaton Corporation",                  "0001551182", null, ["ETN", "Eaton Corporation"]),
        new("ETR",   "Entergy",                            "0000065984", null, ["ETR", "Entergy"]),
        new("EVRG",  "Evergy",                             "0001711269", null, ["EVRG", "Evergy"]),
        new("EW",    "Edwards Lifesciences",               "0001099800", null, ["EW", "Edwards Lifesciences"]),
        new("EXC",   "Exelon",                             "0001109357", null, ["EXC", "Exelon"]),
        new("EXE",   "Expand Energy",                      "0000895126", null, ["EXE", "Expand Energy"]),
        new("EXPD",  "Expeditors International",           "0000746515", null, ["EXPD", "Expeditors International"]),
        new("EXPE",  "Expedia Group",                      "0001324424", null, ["EXPE", "Expedia Group"]),
        new("EXR",   "Extra Space Storage",                "0001289490", null, ["EXR", "Extra Space Storage"]),
        new("F",     "Ford Motor Company",                 "0000037996", null, ["F", "Ford Motor Company"]),
        new("FANG",  "Diamondback Energy",                 "0001539838", null, ["FANG", "Diamondback Energy"]),
        new("FAST",  "Fastenal",                           "0000815556", null, ["FAST", "Fastenal"]),
        new("FCX",   "Freeport-McMoRan Inc.",              "0000831259", null, ["FCX", "Freeport-McMoRan", "Freeport"]),
        new("FDS",   "FactSet",                            "0001013237", null, ["FDS", "FactSet"]),
        new("FDX",   "FedEx",                              "0001048911", null, ["FDX", "FedEx"]),
        new("FE",    "FirstEnergy",                        "0001031296", null, ["FE", "FirstEnergy"]),
        new("FFIV",  "F5, Inc.",                           "0001048695", null, ["FFIV", "F5, Inc."]),
        new("FICO",  "Fair Isaac",                         "0000814547", null, ["FICO", "Fair Isaac"]),
        new("FIS",   "Fidelity National Information Services", "0001136893", null, ["FIS", "Fidelity National Information Services"]),
        new("FISV",  "Fiserv",                             "0000798354", null, ["FISV", "Fiserv"]),
        new("FITB",  "Fifth Third Bancorp",                "0000035527", null, ["FITB", "Fifth Third Bancorp"]),
        new("FIX",   "Comfort Systems USA",                "0001035983", null, ["FIX", "Comfort Systems USA"]),
        new("FOX",   "Fox Corporation (Class B)",          "0001754301", null, ["FOX", "Fox Corporation"]),
        new("FOXA",  "Fox Corporation (Class A)",          "0001754301", null, ["FOXA", "Fox Corporation"]),
        new("FRT",   "Federal Realty Investment Trust",    "0000034903", null, ["FRT", "Federal Realty Investment Trust"]),
        new("FSLR",  "First Solar",                        "0001274494", null, ["FSLR", "First Solar"]),
        new("FTNT",  "Fortinet",                           "0001262039", null, ["FTNT", "Fortinet"]),
        new("FTV",   "Fortive",                            "0001659166", null, ["FTV", "Fortive"]),
        new("GD",    "General Dynamics",                   "0000040533", null, ["GD", "General Dynamics"]),
        new("GDDY",  "GoDaddy",                            "0001609711", null, ["GDDY", "GoDaddy"]),
        new("GE",    "GE Aerospace",                       "0000040545", null, ["GE", "GE Aerospace"]),
        new("GEHC",  "GE HealthCare",                      "0001932393", null, ["GEHC", "GE HealthCare"]),
        new("GEN",   "Gen Digital",                        "0000849399", null, ["GEN", "Gen Digital"]),
        new("GEV",   "GE Vernova",                         "0001996810", null, ["GEV", "GE Vernova"]),
        new("GILD",  "Gilead Sciences",                    "0000882095", null, ["GILD", "Gilead Sciences"]),
        new("GIS",   "General Mills",                      "0000040704", null, ["GIS", "General Mills"]),
        new("GL",    "Globe Life",                         "0000320335", null, ["GL", "Globe Life"]),
        new("GLW",   "Corning Inc.",                       "0000024741", null, ["GLW", "Corning Inc."]),
        new("GM",    "General Motors",                     "0001467858", null, ["GM", "General Motors"]),
        new("GNRC",  "Generac",                            "0001474735", null, ["GNRC", "Generac"]),
        new("GOLD",  "Barrick Gold Corp.",                 "0000756894", null, ["GOLD", "Barrick Gold", "Barrick"]),
        new("GOOGL", "Alphabet Inc.",                      "0001652044", "https://blog.google/rss/", ["GOOGL", "GOOG", "Alphabet", "Google", "Alphabet Inc"]),
        new("GPC",   "Genuine Parts Company",              "0000040987", null, ["GPC", "Genuine Parts Company"]),
        new("GPI",   "Group 1 Automotive Inc.",            "0001031203", null, ["GPI", "Group 1 Automotive"]),
        new("GPN",   "Global Payments",                    "0001123360", null, ["GPN", "Global Payments"]),
        new("GRMN",  "Garmin",                             "0001121788", null, ["GRMN", "Garmin"]),
        new("GS",    "Goldman Sachs",                      "0000886982", null, ["GS", "Goldman Sachs"]),
        new("GWW",   "W. W. Grainger",                     "0000277135", null, ["GWW", "W. W. Grainger"]),
        new("HAL",   "Halliburton Co.",                    "0000045012", null, ["HAL", "Halliburton"]),
        new("HAS",   "Hasbro",                             "0000046080", null, ["HAS", "Hasbro"]),
        new("HBAN",  "Huntington Bancshares",              "0000049196", null, ["HBAN", "Huntington Bancshares"]),
        new("HCA",   "HCA Healthcare",                     "0000860730", null, ["HCA", "HCA Healthcare"]),
        new("HD",    "Home Depot (The)",                   "0000354950", null, ["HD", "Home Depot"]),
        new("HIG",   "Hartford (The)",                     "0000874766", null, ["HIG", "Hartford"]),
        new("HII",   "Huntington Ingalls Industries",      "0001501585", null, ["HII", "Huntington Ingalls Industries"]),
        new("HLT",   "Hilton Worldwide",                   "0001585689", null, ["HLT", "Hilton Worldwide"]),
        new("HON",   "Honeywell",                          "0000773840", null, ["HON", "Honeywell"]),
        new("HOOD",  "Robinhood Markets",                  "0001783879", null, ["HOOD", "Robinhood Markets"]),
        new("HPE",   "Hewlett Packard Enterprise",         "0001645590", null, ["HPE", "Hewlett Packard Enterprise"]),
        new("HPQ",   "HP Inc.",                            "0000047217", null, ["HPQ", "HP Inc."]),
        new("HRL",   "Hormel Foods",                       "0000048465", null, ["HRL", "Hormel Foods"]),
        new("HSIC",  "Henry Schein",                       "0001000228", null, ["HSIC", "Henry Schein"]),
        new("HST",   "Host Hotels & Resorts",              "0001070750", null, ["HST", "Host Hotels & Resorts"]),
        new("HSY",   "Hershey Company (The)",              "0000047111", null, ["HSY", "Hershey Company"]),
        new("HUBB",  "Hubbell Incorporated",               "0000048898", null, ["HUBB", "Hubbell Incorporated"]),
        new("HUM",   "Humana",                             "0000049071", null, ["HUM", "Humana"]),
        new("HWM",   "Howmet Aerospace",                   "0000004281", null, ["HWM", "Howmet Aerospace"]),
        new("IBKR",  "Interactive Brokers",                "0001381197", null, ["IBKR", "Interactive Brokers"]),
        new("IBM",   "IBM",                                "0000051143", null, ["IBM"]),
        new("ICE",   "Intercontinental Exchange",          "0001571949", null, ["ICE", "Intercontinental Exchange"]),
        new("IDXX",  "Idexx Laboratories",                 "0000874716", null, ["IDXX", "Idexx Laboratories"]),
        new("IEX",   "IDEX Corporation",                   "0000832101", null, ["IEX", "IDEX Corporation"]),
        new("IFF",   "International Flavors & Fragrances", "0000051253", null, ["IFF", "International Flavors & Fragrances"]),
        new("IGV",   "iShares Expanded Tech-Software ETF",  "", null, ["IGV"]),
        new("INCY",  "Incyte",                             "0000879169", null, ["INCY", "Incyte"]),
        new("INTC",  "Intel Corp.",                        "0000050863", "https://www.intc.com/rss/news.xml", ["INTC", "Intel", "Intel Corporation"]),
        new("INTU",  "Intuit",                             "0000896878", null, ["INTU", "Intuit"]),
        new("INVH",  "Invitation Homes",                   "0001687229", null, ["INVH", "Invitation Homes"]),
        new("IP",    "International Paper",                "0000051434", null, ["IP", "International Paper"]),
        new("IQV",   "IQVIA",                              "0001478242", null, ["IQV", "IQVIA"]),
        new("IR",    "Ingersoll Rand",                     "0001699150", null, ["IR", "Ingersoll Rand"]),
        new("IRM",   "Iron Mountain",                      "0001020569", null, ["IRM", "Iron Mountain"]),
        new("ISRG",  "Intuitive Surgical",                 "0001035267", null, ["ISRG", "Intuitive Surgical"]),
        new("IT",    "Gartner",                            "0000749251", null, ["IT", "Gartner"]),
        new("ITW",   "Illinois Tool Works",                "0000049826", null, ["ITW", "Illinois Tool Works"]),
        new("IVZ",   "Invesco",                            "0000914208", null, ["IVZ", "Invesco"]),
        new("J",     "Jacobs Solutions",                   "0000052988", null, ["J", "Jacobs Solutions"]),
        new("JBHT",  "J.B. Hunt",                          "0000728535", null, ["JBHT", "J.B. Hunt"]),
        new("JBL",   "Jabil",                              "0000898293", null, ["JBL", "Jabil"]),
        new("JCI",   "Johnson Controls",                   "0000833444", null, ["JCI", "Johnson Controls"]),
        new("JKHY",  "Jack Henry & Associates",            "0000779152", null, ["JKHY", "Jack Henry & Associates"]),
        new("JNJ",   "Johnson & Johnson",                  "0000200406", null, ["JNJ", "Johnson & Johnson"]),
        new("JPM",   "JPMorgan Chase",                     "0000019617", null, ["JPM", "JPMorgan Chase"]),
        new("KAP",   "Kazatomprom",                         "", "https://www.kazatomprom.kz/en/media/press-releases/rss", ["KAP", "Kazatomprom", "NAC Kazatomprom"]),
        new("KDP",   "Keurig Dr Pepper",                   "0001418135", null, ["KDP", "Keurig Dr Pepper"]),
        new("KEY",   "KeyCorp",                            "0000091576", null, ["KEY", "KeyCorp"]),
        new("KEYS",  "Keysight Technologies",              "0001601046", null, ["KEYS", "Keysight Technologies"]),
        new("KHC",   "Kraft Heinz",                        "0001637459", null, ["KHC", "Kraft Heinz"]),
        new("KIM",   "Kimco Realty",                       "0000879101", null, ["KIM", "Kimco Realty"]),
        new("KKR",   "KKR & Co.",                          "0001404912", null, ["KKR", "KKR & Co."]),
        new("KLAC",  "KLA Corp.",                          "0000319201", null, ["KLAC", "KLA Corporation", "KLA-Tencor"]),
        new("KMB",   "Kimberly-Clark",                     "0000055785", null, ["KMB", "Kimberly-Clark"]),
        new("KMI",   "Kinder Morgan",                      "0001506307", null, ["KMI", "Kinder Morgan"]),
        new("KMX",   "CarMax Inc.",                        "0001170010", null, ["KMX", "CarMax"]),
        new("KO",    "Coca-Cola Company (The)",            "0000021344", null, ["KO", "Coca-Cola Company"]),
        new("KR",    "Kroger",                             "0000056873", null, ["KR", "Kroger"]),
        new("KVUE",  "Kenvue",                             "0001944048", null, ["KVUE", "Kenvue"]),
        new("L",     "Loews Corporation",                  "0000060086", null, ["L", "Loews Corporation"]),
        new("LAC",   "Lithium Americas Corp.",             "0001966983", null, ["LAC", "Lithium Americas"]),
        new("LAD",   "Lithia Motors Inc.",                 "0001023128", null, ["LAD", "Lithia Motors", "Lithia"]),
        new("LDOS",  "Leidos",                             "0001336920", null, ["LDOS", "Leidos"]),
        new("LEU",   "Centrus Energy Corp.",               "0001065059", null, ["LEU", "Centrus Energy", "Centrus"]),
        new("LEN",   "Lennar",                             "0000920760", null, ["LEN", "Lennar"]),
        new("LH",    "Labcorp",                            "0000920148", null, ["LH", "Labcorp"]),
        new("LHX",   "L3Harris",                           "0000202058", null, ["LHX", "L3Harris"]),
        new("LII",   "Lennox International",               "0001069202", null, ["LII", "Lennox International"]),
        new("LIT",   "Global X Lithium & Battery Tech ETF", "", null, ["LIT"]),
        new("LIN",   "Linde plc",                          "0001707925", null, ["LIN", "Linde plc"]),
        new("LITE",  "Lumentum",                           "0001633978", null, ["LITE", "Lumentum"]),
        new("LLY",   "Lilly (Eli)",                        "0000059478", null, ["LLY", "Lilly (Eli)"]),
        new("LMT",   "Lockheed Martin",                    "0000936468", null, ["LMT", "Lockheed Martin"]),
        new("LNT",   "Alliant Energy",                     "0000352541", null, ["LNT", "Alliant Energy"]),
        new("LOW",   "Lowe's",                             "0000060667", null, ["LOW", "Lowe's"]),
        new("LRCX",  "Lam Research Corp.",                 "0000707549", null, ["LRCX", "Lam Research"]),
        new("LULU",  "Lululemon Athletica",                "0001397187", null, ["LULU", "Lululemon Athletica"]),
        new("LUV",   "Southwest Airlines",                 "0000092380", null, ["LUV", "Southwest Airlines"]),
        new("LVS",   "Las Vegas Sands",                    "0001300514", null, ["LVS", "Las Vegas Sands"]),
        new("LYB",   "LyondellBasell",                     "0001489393", null, ["LYB", "LyondellBasell"]),
        new("LYV",   "Live Nation Entertainment",          "0001335258", null, ["LYV", "Live Nation Entertainment"]),
        new("MA",    "Mastercard",                         "0001141391", null, ["MA", "Mastercard"]),
        new("MAA",   "Mid-America Apartment Communities",  "0000912595", null, ["MAA", "Mid-America Apartment Communities"]),
        new("MAR",   "Marriott International",             "0001048286", null, ["MAR", "Marriott International"]),
        new("MAS",   "Masco",                              "0000062996", null, ["MAS", "Masco"]),
        new("MCD",   "McDonald's",                         "0000063908", null, ["MCD", "McDonald's"]),
        new("MDB",   "MongoDB Inc.",                       "0001441816", null, ["MDB", "MongoDB"]),
        new("MCHP",  "Microchip Technology",               "0000827054", null, ["MCHP", "Microchip Technology"]),
        new("MCK",   "McKesson Corporation",               "0000927653", null, ["MCK", "McKesson Corporation"]),
        new("MCO",   "Moody's Corporation",                "0001059556", null, ["MCO", "Moody's Corporation"]),
        new("MDLZ",  "Mondelez International",             "0001103982", null, ["MDLZ", "Mondelez International"]),
        new("MDT",   "Medtronic",                          "0001613103", null, ["MDT", "Medtronic"]),
        new("MET",   "MetLife",                            "0001099219", null, ["MET", "MetLife"]),
        new("META",  "Meta Platforms Inc.",                "0001326801", null, ["META", "Meta", "Meta Platforms", "Facebook"]),
        new("MGM",   "MGM Resorts",                        "0000789570", null, ["MGM", "MGM Resorts"]),
        new("MKC",   "McCormick & Company",                "0000063754", null, ["MKC", "McCormick & Company"]),
        new("MLM",   "Martin Marietta Materials",          "0000916076", null, ["MLM", "Martin Marietta Materials"]),
        new("MMM",   "3M",                                 "0000066740", null, ["MMM", "3M"]),
        new("MNST",  "Monster Beverage",                   "0000865752", null, ["MNST", "Monster Beverage"]),
        new("MO",    "Altria",                             "0000764180", null, ["MO", "Altria"]),
        new("MOS",   "Mosaic Company (The)",               "0001285785", null, ["MOS", "Mosaic Company"]),
        new("MP",    "MP Materials Corp.",                 "0001801368", null, ["MP", "MP Materials"]),
        new("MPC",   "Marathon Petroleum",                 "0001510295", null, ["MPC", "Marathon Petroleum"]),
        new("MPWR",  "Monolithic Power Systems",           "0001280452", null, ["MPWR", "Monolithic Power Systems"]),
        new("MRK",   "Merck & Co.",                        "0000310158", null, ["MRK", "Merck & Co."]),
        new("MRNA",  "Moderna",                            "0001682852", null, ["MRNA", "Moderna"]),
        new("MRSH",  "Marsh McLennan",                     "0000062709", null, ["MRSH", "Marsh McLennan"]),
        new("MRVL",  "Marvell Technology Inc.",            "0001835632", null, ["MRVL", "Marvell", "Marvell Technology"]),
        new("MS",    "Morgan Stanley",                     "0000895421", null, ["MS", "Morgan Stanley"]),
        new("MSCI",  "MSCI Inc.",                          "0001408198", null, ["MSCI", "MSCI Inc."]),
        new("MSFT",  "Microsoft Corp.",                    "0000789019", "https://news.microsoft.com/feed/", ["MSFT", "Microsoft"]),
        new("MSI",   "Motorola Solutions",                 "0000068505", null, ["MSI", "Motorola Solutions"]),
        new("MTB",   "M&T Bank",                           "0000036270", null, ["MTB", "M&T Bank"]),
        new("MTD",   "Mettler Toledo",                     "0001037646", null, ["MTD", "Mettler Toledo"]),
        new("MU",    "Micron Technology Inc.",             "0000723125", "https://investors.micron.com/rss/news-releases.xml", ["MU", "Micron", "Micron Technology"]),
        new("NBIS",  "Nebius Group N.V.",                  "0001513845", null, ["NBIS", "Nebius"]),
        new("NCLH",  "Norwegian Cruise Line Holdings",     "0001513761", null, ["NCLH", "Norwegian Cruise Line Holdings"]),
        new("NDAQ",  "Nasdaq, Inc.",                       "0001120193", null, ["NDAQ", "Nasdaq, Inc."]),
        new("NDSN",  "Nordson Corporation",                "0000072331", null, ["NDSN", "Nordson Corporation"]),
        new("NEE",   "NextEra Energy",                     "0000753308", null, ["NEE", "NextEra Energy"]),
        new("NEM",   "Newmont Corp.",                      "0001164727", null, ["NEM", "Newmont", "Newmont Mining"]),
        new("NET",   "Cloudflare Inc.",                    "0001477333", null, ["NET", "Cloudflare"]),
        new("NFLX",  "Netflix",                            "0001065280", null, ["NFLX", "Netflix"]),
        new("NI",    "NiSource",                           "0001111711", null, ["NI", "NiSource"]),
        new("NKE",   "Nike, Inc.",                         "0000320187", null, ["NKE", "Nike, Inc."]),
        new("NOC",   "Northrop Grumman",                   "0001133421", null, ["NOC", "Northrop Grumman"]),
        new("NOW",   "ServiceNow Inc.",                    "0001373715", null, ["NOW", "ServiceNow"]),
        new("NRG",   "NRG Energy",                         "0001013871", null, ["NRG", "NRG Energy"]),
        new("NSC",   "Norfolk Southern",                   "0000702165", null, ["NSC", "Norfolk Southern"]),
        new("NTAP",  "NetApp",                             "0001002047", null, ["NTAP", "NetApp"]),
        new("NTRS",  "Northern Trust",                     "0000073124", null, ["NTRS", "Northern Trust"]),
        new("NUE",   "Nucor",                              "0000073309", null, ["NUE", "Nucor"]),
        new("NVDA",  "NVIDIA Corp.",                       "0001045810", "https://nvidianews.nvidia.com/releases.xml", ["NVDA", "Nvidia", "NVIDIA", "NVIDIA Corporation", "NVIDIA Corp"]),
        new("NVR",   "NVR, Inc.",                          "0000906163", null, ["NVR", "NVR, Inc."]),
        new("NWS",   "News Corp (Class B)",                "0001564708", null, ["NWS", "News Corp"]),
        new("NWSA",  "News Corp (Class A)",                "0001564708", null, ["NWSA", "News Corp"]),
        new("NXE",   "NexGen Energy Ltd.",                 "0001698535", null, ["NXE", "NexGen Energy", "NexGen"]),
        new("NXPI",  "NXP Semiconductors NV",              "0001413447", null, ["NXPI", "NXP Semiconductors", "NXP"]),
        new("O",     "Realty Income",                      "0000726728", null, ["O", "Realty Income"]),
        new("ODFL",  "Old Dominion",                       "0000878927", null, ["ODFL", "Old Dominion"]),
        new("OKE",   "Oneok",                              "0001039684", null, ["OKE", "Oneok"]),
        new("OMC",   "Omnicom Group",                      "0000029989", null, ["OMC", "Omnicom Group"]),
        new("ON",    "ON Semiconductor Corp.",             "0001097864", null, ["ON Semiconductor", "onsemi"]),
        new("ORCL",  "Oracle Corp.",                       "0001341439", "https://www.oracle.com/corporate/press/rss/rss-pr.xml", ["ORCL", "Oracle"]),
        new("ORLY",  "O’Reilly Automotive",                "0000898173", null, ["ORLY", "O’Reilly Automotive"]),
        new("OTIS",  "Otis Worldwide",                     "0001781335", null, ["OTIS", "Otis Worldwide"]),
        new("OXY",   "Occidental Petroleum Corp.",         "0000797468", null, ["OXY", "Occidental", "Occidental Petroleum"]),
        new("PAG",   "Penske Automotive Group Inc.",       "0001019849", null, ["PAG", "Penske Automotive"]),
        new("PANW",  "Palo Alto Networks",                 "0001327567", null, ["PANW", "Palo Alto Networks"]),
        new("PATH",  "UiPath Inc.",                        "0001734722", null, ["PATH", "UiPath"]),
        new("PAYX",  "Paychex",                            "0000723531", null, ["PAYX", "Paychex"]),
        new("PCAR",  "Paccar",                             "0000075362", null, ["PCAR", "Paccar"]),
        new("PCG",   "PG&E Corporation",                   "0001004980", null, ["PCG", "PG&E Corporation"]),
        new("PEG",   "Public Service Enterprise Group",    "0000788784", null, ["PEG", "Public Service Enterprise Group"]),
        new("PEP",   "PepsiCo",                            "0000077476", null, ["PEP", "PepsiCo"]),
        new("PFE",   "Pfizer",                             "0000078003", null, ["PFE", "Pfizer"]),
        new("PFG",   "Principal Financial Group",          "0001126328", null, ["PFG", "Principal Financial Group"]),
        new("PG",    "Procter & Gamble",                   "0000080424", null, ["PG", "Procter & Gamble"]),
        new("PGR",   "Progressive Corporation",            "0000080661", null, ["PGR", "Progressive Corporation"]),
        new("PH",    "Parker Hannifin",                    "0000076334", null, ["PH", "Parker Hannifin"]),
        new("PHM",   "PulteGroup",                         "0000822416", null, ["PHM", "PulteGroup"]),
        new("PKG",   "Packaging Corporation of America",   "0000075677", null, ["PKG", "Packaging Corporation of America"]),
        new("PLD",   "Prologis",                           "0001045609", null, ["PLD", "Prologis"]),
        new("PLTR",  "Palantir Technologies Inc.",         "0001321655", null, ["PLTR", "Palantir"]),
        new("PM",    "Philip Morris International",        "0001413329", null, ["PM", "Philip Morris International"]),
        new("PNC",   "PNC Financial Services",             "0000713676", null, ["PNC", "PNC Financial Services"]),
        new("PNR",   "Pentair",                            "0000077360", null, ["PNR", "Pentair"]),
        new("PNW",   "Pinnacle West Capital",              "0000764622", null, ["PNW", "Pinnacle West Capital"]),
        new("PODD",  "Insulet Corporation",                "0001145197", null, ["PODD", "Insulet Corporation"]),
        new("POOL",  "Pool Corporation",                   "0000945841", null, ["POOL", "Pool Corporation"]),
        new("PPG",   "PPG Industries",                     "0000079879", null, ["PPG", "PPG Industries"]),
        new("PPL",   "PPL Corporation",                    "0000922224", null, ["PPL", "PPL Corporation"]),
        new("PRU",   "Prudential Financial",               "0001137774", null, ["PRU", "Prudential Financial"]),
        new("PSA",   "Public Storage",                     "0001393311", null, ["PSA", "Public Storage"]),
        new("PSKY",  "Paramount Skydance Corporation",     "0002041610", null, ["PSKY", "Paramount Skydance Corporation"]),
        new("PSX",   "Phillips 66",                        "0001534701", null, ["PSX", "Phillips 66"]),
        new("PTC",   "PTC Inc.",                           "0000857005", null, ["PTC", "PTC Inc."]),
        new("PWR",   "Quanta Services",                    "0001050915", null, ["PWR", "Quanta Services"]),
        new("PYPL",  "PayPal",                             "0001633917", null, ["PYPL", "PayPal"]),
        new("Q",     "Qnity Electronics",                  "0002058873", null, ["Q", "Qnity Electronics"]),
        new("QCOM",  "Qualcomm Inc.",                      "0000804328", "https://investor.qualcomm.com/rss/news-releases.xml", ["QCOM", "Qualcomm"]),
        new("QQQ",   "Invesco QQQ Trust",                  "", null, ["QQQ"]),
        new("RDDT",  "Reddit Inc.",                         "0001713445", null, ["RDDT", "Reddit"]),
        new("RCL",   "Royal Caribbean Group",              "0000884887", null, ["RCL", "Royal Caribbean Group"]),
        new("REG",   "Regency Centers",                    "0000910606", null, ["REG", "Regency Centers"]),
        new("REGN",  "Regeneron Pharmaceuticals",          "0000872589", null, ["REGN", "Regeneron Pharmaceuticals"]),
        new("RF",    "Regions Financial Corporation",      "0001281761", null, ["RF", "Regions Financial Corporation"]),
        new("RIO",   "Rio Tinto plc",                      "0000863064", null, ["RIO", "Rio Tinto"]),
        new("RJF",   "Raymond James Financial",            "0000720005", null, ["RJF", "Raymond James Financial"]),
        new("RL",    "Ralph Lauren Corporation",           "0001037038", null, ["RL", "Ralph Lauren Corporation"]),
        new("RMD",   "ResMed",                             "0000943819", null, ["RMD", "ResMed"]),
        new("ROK",   "Rockwell Automation",                "0001024478", null, ["ROK", "Rockwell Automation"]),
        new("ROL",   "Rollins, Inc.",                      "0000084839", null, ["ROL", "Rollins, Inc."]),
        new("ROP",   "Roper Technologies",                 "0000882835", null, ["ROP", "Roper Technologies"]),
        new("ROST",  "Ross Stores",                        "0000745732", null, ["ROST", "Ross Stores"]),
        new("RSG",   "Republic Services",                  "0001060391", null, ["RSG", "Republic Services"]),
        new("RTX",   "RTX Corporation",                    "0000101829", null, ["RTX", "RTX Corporation"]),
        new("RVTY",  "Revvity",                            "0000031791", null, ["RVTY", "Revvity"]),
        new("SATS",  "EchoStar",                           "0001415404", null, ["SATS", "EchoStar"]),
        new("SBAC",  "SBA Communications",                 "0001034054", null, ["SBAC", "SBA Communications"]),
        new("SBUX",  "Starbucks",                          "0000829224", null, ["SBUX", "Starbucks"]),
        new("SCCO",  "Southern Copper Corp.",              "0001001838", null, ["SCCO", "Southern Copper"]),
        new("SCHW",  "Charles Schwab Corporation",         "0000316709", null, ["SCHW", "Charles Schwab Corporation"]),
        new("SGML",  "Sigma Lithium Corp.",                "0001848309", null, ["SGML", "Sigma Lithium"]),
        new("SHW",   "Sherwin-Williams",                   "0000089800", null, ["SHW", "Sherwin-Williams"]),
        new("SJM",   "J.M. Smucker Company (The)",         "0000091419", null, ["SJM", "J.M. Smucker Company"]),
        new("SLB",   "Schlumberger Limited",               "0000087347", null, ["SLB", "Schlumberger"]),
        new("SMH",   "VanEck Semiconductor ETF",            "", null, ["SMH"]),
        new("SMCI",  "Super Micro Computer Inc.",          "0001375365", null, ["SMCI", "Super Micro", "Supermicro"]),
        new("SNA",   "Snap-on",                            "0000091440", null, ["SNA", "Snap-on"]),
        new("SNDK",  "Sandisk",                            "0002023554", null, ["SNDK", "Sandisk"]),
        new("SNOW",  "Snowflake Inc.",                     "0001640147", null, ["SNOW", "Snowflake"]),
        new("SNPS",  "Synopsys",                           "0000883241", null, ["SNPS", "Synopsys"]),
        new("SO",    "Southern Company",                   "0000092122", null, ["SO", "Southern Company"]),
        new("SOLV",  "Solventum",                          "0001964738", null, ["SOLV", "Solventum"]),
        new("SPG",   "Simon Property Group",               "0001063761", null, ["SPG", "Simon Property Group"]),
        new("SPGI",  "S&P Global",                         "0000064040", null, ["SPGI", "S&P Global"]),
        new("SRE",   "Sempra",                             "0001032208", null, ["SRE", "Sempra"]),
        new("STE",   "Steris",                             "0001757898", null, ["STE", "Steris"]),
        new("STLD",  "Steel Dynamics",                     "0001022671", null, ["STLD", "Steel Dynamics"]),
        new("STT",   "State Street Corporation",           "0000093751", null, ["STT", "State Street Corporation"]),
        new("STX",   "Seagate Technology",                 "0001137789", null, ["STX", "Seagate Technology"]),
        new("STZ",   "Constellation Brands",               "0000016918", null, ["STZ", "Constellation Brands"]),
        new("SW",    "Smurfit Westrock",                   "0002005951", null, ["SW", "Smurfit Westrock"]),
        new("SWK",   "Stanley Black & Decker",             "0000093556", null, ["SWK", "Stanley Black & Decker"]),
        new("SWKS",  "Skyworks Solutions",                 "0000004127", null, ["SWKS", "Skyworks Solutions"]),
        new("SYF",   "Synchrony Financial",                "0001601712", null, ["SYF", "Synchrony Financial"]),
        new("SYK",   "Stryker Corporation",                "0000310764", null, ["SYK", "Stryker Corporation"]),
        new("SYY",   "Sysco",                              "0000096021", null, ["SYY", "Sysco"]),
        new("T",     "AT&T",                               "0000732717", null, ["T", "AT&T"]),
        new("TAP",   "Molson Coors Beverage Company",      "0000024545", null, ["TAP", "Molson Coors Beverage Company"]),
        new("TDG",   "TransDigm Group",                    "0001260221", null, ["TDG", "TransDigm Group"]),
        new("TDY",   "Teledyne Technologies",              "0001094285", null, ["TDY", "Teledyne Technologies"]),
        new("TECH",  "Bio-Techne",                         "0000842023", null, ["TECH", "Bio-Techne"]),
        new("TECK",  "Teck Resources Limited",             "0000886986", null, ["TECK", "Teck Resources", "Teck"]),
        new("TEL",   "TE Connectivity",                    "0001385157", null, ["TEL", "TE Connectivity"]),
        new("TER",   "Teradyne",                           "0000097210", null, ["TER", "Teradyne"]),
        new("TFC",   "Truist Financial",                   "0000092230", null, ["TFC", "Truist Financial"]),
        new("TGT",   "Target Corporation",                 "0000027419", null, ["TGT", "Target Corporation"]),
        new("TJX",   "TJX Companies",                      "0000109198", null, ["TJX", "TJX Companies"]),
        new("TKO",   "TKO Group Holdings",                 "0001973266", null, ["TKO", "TKO Group Holdings"]),
        new("TMO",   "Thermo Fisher Scientific",           "0000097745", null, ["TMO", "Thermo Fisher Scientific"]),
        new("TMUS",  "T-Mobile US",                        "0001283699", null, ["TMUS", "T-Mobile US"]),
        new("TPL",   "Texas Pacific Land Corporation",     "0001811074", null, ["TPL", "Texas Pacific Land Corporation"]),
        new("TPR",   "Tapestry, Inc.",                     "0001116132", null, ["TPR", "Tapestry, Inc."]),
        new("TRGP",  "Targa Resources",                    "0001389170", null, ["TRGP", "Targa Resources"]),
        new("TRMB",  "Trimble Inc.",                       "0000864749", null, ["TRMB", "Trimble Inc."]),
        new("TROW",  "T. Rowe Price",                      "0001113169", null, ["TROW", "T. Rowe Price"]),
        new("TRV",   "Travelers Companies (The)",          "0000086312", null, ["TRV", "Travelers Companies"]),
        new("TSCO",  "Tractor Supply",                     "0000916365", null, ["TSCO", "Tractor Supply"]),
        new("TSLA",  "Tesla, Inc.",                        "0001318605", null, ["TSLA", "Tesla, Inc."]),
        new("TSM",   "Taiwan Semiconductor Mfg.",          "0001046179", null, ["TSM", "TSMC", "Taiwan Semiconductor", "Taiwan Semiconductor Manufacturing"]),
        new("TSN",   "Tyson Foods",                        "0000100493", null, ["TSN", "Tyson Foods"]),
        new("TT",    "Trane Technologies",                 "0001466258", null, ["TT", "Trane Technologies"]),
        new("TTD",   "Trade Desk (The)",                   "0001671933", null, ["TTD", "Trade Desk"]),
        new("TTWO",  "Take-Two Interactive",               "0000946581", null, ["TTWO", "Take-Two Interactive"]),
        new("TXN",   "Texas Instruments Inc.",             "0000097476", null, ["TXN", "Texas Instruments"]),
        new("TXT",   "Textron",                            "0000217346", null, ["TXT", "Textron"]),
        new("TYL",   "Tyler Technologies",                 "0000860731", null, ["TYL", "Tyler Technologies"]),
        new("UAL",   "United Airlines Holdings",           "0000100517", null, ["UAL", "United Airlines Holdings"]),
        new("UBER",  "Uber",                               "0001543151", null, ["UBER", "Uber"]),
        new("UDR",   "UDR, Inc.",                          "0000074208", null, ["UDR", "UDR, Inc."]),
        new("UEC",   "Uranium Energy Corp.",               "0001334933", null, ["UEC", "Uranium Energy", "Uranium Energy Corp"]),
        new("UHS",   "Universal Health Services",          "0000352915", null, ["UHS", "Universal Health Services"]),
        new("ULTA",  "Ulta Beauty",                        "0001403568", null, ["ULTA", "Ulta Beauty"]),
        new("UNH",   "UnitedHealth Group",                 "0000731766", null, ["UNH", "UnitedHealth Group"]),
        new("UNP",   "Union Pacific Corporation",          "0000100885", null, ["UNP", "Union Pacific Corporation"]),
        new("UPS",   "United Parcel Service",              "0001090727", null, ["UPS", "United Parcel Service"]),
        new("URI",   "United Rentals",                     "0001067701", null, ["URI", "United Rentals"]),
        new("URNM",  "Sprott Uranium Miners ETF",          "", null, ["URNM"]),
        new("UUUU",  "Energy Fuels Inc.",                  "0001385849", null, ["UUUU", "Energy Fuels"]),
        new("USB",   "U.S. Bancorp",                       "0000036104", null, ["USB", "U.S. Bancorp"]),
        new("V",     "Visa Inc.",                          "0001403161", null, ["V", "Visa Inc."]),
        new("VEEV",  "Veeva Systems",                      "0001393052", null, ["VEEV", "Veeva Systems"]),
        new("VICI",  "Vici Properties",                    "0001705696", null, ["VICI", "Vici Properties"]),
        new("VLO",   "Valero Energy",                      "0001035002", null, ["VLO", "Valero Energy"]),
        new("VLTO",  "Veralto",                            "0001967680", null, ["VLTO", "Veralto"]),
        new("VMC",   "Vulcan Materials Company",           "0001396009", null, ["VMC", "Vulcan Materials Company"]),
        new("VRSK",  "Verisk Analytics",                   "0001442145", null, ["VRSK", "Verisk Analytics"]),
        new("VRSN",  "Verisign",                           "0001014473", null, ["VRSN", "Verisign"]),
        new("VRT",   "Vertiv",                             "0001674101", null, ["VRT", "Vertiv"]),
        new("VRTX",  "Vertex Pharmaceuticals",             "0000875320", null, ["VRTX", "Vertex Pharmaceuticals"]),
        new("VST",   "Vistra Corp.",                       "0001692819", null, ["VST", "Vistra Corp."]),
        new("VTR",   "Ventas",                             "0000740260", null, ["VTR", "Ventas"]),
        new("VTRS",  "Viatris",                            "0001792044", null, ["VTRS", "Viatris"]),
        new("VZ",    "Verizon",                            "0000732712", null, ["VZ", "Verizon"]),
        new("WAB",   "Wabtec",                             "0000943452", null, ["WAB", "Wabtec"]),
        new("WAT",   "Waters Corporation",                 "0001000697", null, ["WAT", "Waters Corporation"]),
        new("WBD",   "Warner Bros. Discovery",             "0001437107", null, ["WBD", "Warner Bros. Discovery"]),
        new("WDAY",  "Workday, Inc.",                      "0001327811", null, ["WDAY", "Workday, Inc."]),
        new("WDC",   "Western Digital",                    "0000106040", null, ["WDC", "Western Digital"]),
        new("WEC",   "WEC Energy Group",                   "0000783325", null, ["WEC", "WEC Energy Group"]),
        new("WELL",  "Welltower",                          "0000766704", null, ["WELL", "Welltower"]),
        new("WFC",   "Wells Fargo",                        "0000072971", null, ["WFC", "Wells Fargo"]),
        new("WM",    "Waste Management",                   "0000823768", null, ["WM", "Waste Management"]),
        new("WMB",   "Williams Companies",                 "0000107263", null, ["WMB", "Williams Companies"]),
        new("WMT",   "Walmart",                            "0000104169", null, ["WMT", "Walmart"]),
        new("WOLF",  "Wolfspeed Inc.",                     "0000895419", null, ["WOLF", "Wolfspeed", "Cree"]),
        new("WPM",   "Wheaton Precious Metals Corp.",      "0001323404", null, ["WPM", "Wheaton Precious Metals", "Wheaton"]),
        new("WRB",   "W. R. Berkley Corporation",          "0000011544", null, ["WRB", "W. R. Berkley Corporation"]),
        new("WSM",   "Williams-Sonoma, Inc.",              "0000719955", null, ["WSM", "Williams-Sonoma, Inc."]),
        new("WST",   "West Pharmaceutical Services",       "0000105770", null, ["WST", "West Pharmaceutical Services"]),
        new("WTW",   "Willis Towers Watson",               "0001140536", null, ["WTW", "Willis Towers Watson"]),
        new("WY",    "Weyerhaeuser",                       "0000106535", null, ["WY", "Weyerhaeuser"]),
        new("WYNN",  "Wynn Resorts",                       "0001174922", null, ["WYNN", "Wynn Resorts"]),
        new("XEL",   "Xcel Energy",                        "0000072903", null, ["XEL", "Xcel Energy"]),
        new("XLU",   "Utilities Select Sector SPDR ETF",    "", null, ["XLU"]),
        new("XOM",   "Exxon Mobil Corp.",                  "0000034088", null, ["XOM", "Exxon", "ExxonMobil", "Exxon Mobil"]),
        new("XYL",   "Xylem Inc.",                         "0001524472", null, ["XYL", "Xylem Inc."]),
        new("XYZ",   "Block, Inc.",                        "0001512673", null, ["XYZ", "Block, Inc."]),
        new("YUM",   "Yum! Brands",                        "0001041061", null, ["YUM", "Yum! Brands"]),
        new("ZBH",   "Zimmer Biomet",                      "0001136869", null, ["ZBH", "Zimmer Biomet"]),
        new("ZBRA",  "Zebra Technologies",                 "0000877212", null, ["ZBRA", "Zebra Technologies"]),
        new("ZTS",   "Zoetis",                             "0001555280", null, ["ZTS", "Zoetis"]),
    };

    public static IReadOnlyDictionary<string, TickerMetadataEntry> ByTicker { get; } =
        Known.ToDictionary(e => e.Ticker, StringComparer.OrdinalIgnoreCase);

    public static IReadOnlyDictionary<string, TickerMetadataEntry> ByCik { get; } =
        Known
            .GroupBy(e => e.Cik)
            .ToDictionary(g => g.Key, g => g.First());

    public static TickerMetadataEntry? Lookup(string ticker)
        => ByTicker.TryGetValue(ticker, out var entry) ? entry : null;
}
