// <auto-generated />
using System;
using MarketLens.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MarketLens.Infrastructure.Migrations
{
    [DbContext(typeof(MarketLensDbContext))]
    [Migration("20260503184620_AddFilingChunks")]
    partial class AddFilingChunks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketLens.Core.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceTier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("Symbol");

                    b.HasIndex("Source", "SourceId")
                        .IsUnique();

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ArticleChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)");

                    b.Property<string>("Section")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ArticleId", "ChunkIndex");

                    b.ToTable("article_chunks", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.Cluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DominantSourceTier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TopSourceWeight")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<decimal?>("TriageConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("TriageEventType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("FirstSeenAt");

                    b.HasIndex("Symbol");

                    b.HasIndex("TriageEventType");

                    b.ToTable("clusters", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.EconomicEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTimeSpecific")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("EventType");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Source", "SourceId")
                        .IsUnique();

                    b.HasIndex("Symbol", "ScheduledAt");

                    b.ToTable("economic_events", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.Event", b =>
                {
                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EventClassPrior")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Importance")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<decimal>("MagnitudeSignal")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("NoveltyWeight")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Sentiment")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("Slots")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("SourceWeight")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClusterId");

                    b.HasIndex("EventType");

                    b.HasIndex("Importance");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.MarketSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("AverageVolume")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("BenchmarkMovePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("BenchmarkSymbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("HighPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("IsAfterHours")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LastPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("LowPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("MovePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<decimal?>("OpenPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("PreviousClose")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("QuoteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("ReactionScore")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal?>("RelativeMovePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<decimal?>("RelativeVolume")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("Symbol");

                    b.HasIndex("ClusterId", "CapturedAt");

                    b.ToTable("market_snapshots", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.PriceBar", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Interval")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Symbol", "Interval", "Timestamp");

                    b.HasIndex("Symbol", "Interval", "Timestamp");

                    b.ToTable("price_bars", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ResearchAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("Name");

                    b.HasIndex("Symbol");

                    b.ToTable("research_assets", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ResearchEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArticleChunkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MatchReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewerNote")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal?>("Similarity")
                        .HasPrecision(6, 5)
                        .HasColumnType("numeric(6,5)");

                    b.Property<string>("Stance")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("StanceConfidence")
                        .HasPrecision(6, 5)
                        .HasColumnType("numeric(6,5)");

                    b.Property<string>("StanceModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StancePromptVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StanceRationale")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("ThesisId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ThesisRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TranscriptSegmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArticleChunkId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ClusterId");

                    b.HasIndex("MatchedAt");

                    b.HasIndex("ThesisRuleId");

                    b.HasIndex("TranscriptSegmentId");

                    b.HasIndex("ThesisId", "ArticleChunkId")
                        .IsUnique()
                        .HasFilter("\"ArticleChunkId\" IS NOT NULL");

                    b.HasIndex("ThesisId", "ReviewStatus");

                    b.HasIndex("ThesisId", "Stance");

                    b.HasIndex("ThesisId", "TranscriptSegmentId")
                        .IsUnique()
                        .HasFilter("\"TranscriptSegmentId\" IS NOT NULL");

                    b.HasIndex("ThesisId", "ThesisRuleId", "ArticleId")
                        .IsUnique()
                        .HasFilter("\"ArticleId\" IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ThesisId", "ThesisRuleId", "ArticleId"), false);

                    b.HasIndex("ThesisId", "ThesisRuleId", "ClusterId")
                        .IsUnique()
                        .HasFilter("\"ClusterId\" IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ThesisId", "ThesisRuleId", "ClusterId"), false);

                    b.ToTable("research_evidence", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ResearchSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LatestEvidenceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ThesisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThesisId", "SnapshotAt");

                    b.ToTable("research_snapshots", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ResearchThesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)");

                    b.Property<DateTime?>("LastChunkMatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSegmentMatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Plan")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("PlanGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PlanPromptVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("ThesisText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("research_theses", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.SuppressionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("EventType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<DateTime>("SuppressedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Reason");

                    b.HasIndex("Stage");

                    b.HasIndex("SuppressedAt");

                    b.HasIndex("Symbol");

                    b.HasIndex("Source", "SourceId", "Stage", "Reason")
                        .IsUnique();

                    b.ToTable("suppressions", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ThesisAsset", b =>
                {
                    b.Property<Guid>("ThesisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ThesisId", "AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("thesis_assets", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ThesisRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetKeywords")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ConceptKeywords")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ExcludeTerms")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MinArticleSimilarity")
                        .HasPrecision(6, 5)
                        .HasColumnType("numeric(6,5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceTiers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ThesisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ThesisId", "IsEnabled");

                    b.ToTable("thesis_rules", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.Transcript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("CallDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CallType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("DurationSeconds")
                        .HasColumnType("real");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SegmentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CallDate");

                    b.HasIndex("Status");

                    b.HasIndex("Symbol");

                    b.ToTable("transcripts", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.TranscriptSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1024)");

                    b.Property<float>("EndSeconds")
                        .HasColumnType("real");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Speaker")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<float>("StartSeconds")
                        .HasColumnType("real");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TranscriptId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TranscriptId", "SegmentIndex");

                    b.ToTable("transcript_segments", (string)null);
                });

            modelBuilder.Entity("MarketLens.Core.Entities.Article", b =>
                {
                    b.HasOne("MarketLens.Core.Entities.Cluster", "Cluster")
                        .WithMany("Articles")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ArticleChunk", b =>
                {
                    b.HasOne("MarketLens.Core.Entities.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.EconomicEvent", b =>
                {
                    b.HasOne("MarketLens.Core.Entities.Cluster", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.Event", b =>
                {
                    b.HasOne("MarketLens.Core.Entities.Cluster", "Cluster")
                        .WithOne("Event")
                        .HasForeignKey("MarketLens.Core.Entities.Event", "ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.MarketSnapshot", b =>
                {
                    b.HasOne("MarketLens.Core.Entities.Event", "Event")
                        .WithMany("MarketSnapshots")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ResearchEvidence", b =>
                {
                    b.HasOne("MarketLens.Core.Entities.ArticleChunk", "ArticleChunk")
                        .WithMany()
                        .HasForeignKey("ArticleChunkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarketLens.Core.Entities.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarketLens.Core.Entities.Cluster", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarketLens.Core.Entities.ResearchThesis", "Thesis")
                        .WithMany("Evidence")
                        .HasForeignKey("ThesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketLens.Core.Entities.ThesisRule", "ThesisRule")
                        .WithMany("Evidence")
                        .HasForeignKey("ThesisRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarketLens.Core.Entities.TranscriptSegment", "TranscriptSegment")
                        .WithMany()
                        .HasForeignKey("TranscriptSegmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Article");

                    b.Navigation("ArticleChunk");

                    b.Navigation("Cluster");

                    b.Navigation("Thesis");

                    b.Navigation("ThesisRule");

                    b.Navigation("TranscriptSegment");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ResearchSnapshot", b =>
                {
                    b.HasOne("MarketLens.Core.Entities.ResearchThesis", "Thesis")
                        .WithMany("Snapshots")
                        .HasForeignKey("ThesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thesis");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ThesisAsset", b =>
                {
                    b.HasOne("MarketLens.Core.Entities.ResearchAsset", "Asset")
                        .WithMany("ThesisAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketLens.Core.Entities.ResearchThesis", "Thesis")
                        .WithMany("ThesisAssets")
                        .HasForeignKey("ThesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Thesis");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ThesisRule", b =>
                {
                    b.HasOne("MarketLens.Core.Entities.ResearchThesis", "Thesis")
                        .WithMany("Rules")
                        .HasForeignKey("ThesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thesis");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.Transcript", b =>
                {
                    b.HasOne("MarketLens.Core.Entities.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Article");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.TranscriptSegment", b =>
                {
                    b.HasOne("MarketLens.Core.Entities.Transcript", "Transcript")
                        .WithMany("Segments")
                        .HasForeignKey("TranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.Cluster", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.Event", b =>
                {
                    b.Navigation("MarketSnapshots");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ResearchAsset", b =>
                {
                    b.Navigation("ThesisAssets");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ResearchThesis", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("Rules");

                    b.Navigation("Snapshots");

                    b.Navigation("ThesisAssets");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.ThesisRule", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("MarketLens.Core.Entities.Transcript", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
